### ISSUE TITLE
Add to Technical Majority?

### ISSUE THREAD

**Issue by phildini** [katerabinowitz/Code-Against-Trump#1]
Hey there @katerabinowitz! I run technicalmajority.com, where we're trying to catalog all the resources for tech activism. If you're willing, you can file a PR against https://github.com/phildini/technicalmajority, or I can add what you've listed here to the list we have going.

Also: Any feedback you have on Technical Majority is super appreciated!

**Comment by katerabinowitz** [comment]
Cool, thanks for sharing @phildini! Definitely feel free to add what's listed here to your site. One thing I'll note from your site is that BetaNYC is a Code for America brigade. They're great! Unless there's a specific reason for calling them out, you may want to consider having a more general Code for America brigades section (which includes groups like BetaNYC, ChiHackNight, Code for DC, etc) and a link to find your local brigade (or start your own!) http://brigade.codeforamerica.org/brigade/
